name: Build Chromium

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
 run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Run the batch file
        run: .\main.bat
